# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Timescales

import flatbuffers

class Message(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMessage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Message()
        x.Init(buf, n + offset)
        return x

    # Message
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Message
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from .NullableInt64 import NullableInt64
            obj = NullableInt64()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Message
    def PropP(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from .NullableBool import NullableBool
            obj = NullableBool()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Message
    def PropQ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .NullableBool import NullableBool
            obj = NullableBool()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Message
    def PropR(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            from .NullableBool import NullableBool
            obj = NullableBool()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Message
    def PropS(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from .NullableBool import NullableBool
            obj = NullableBool()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MessageStart(builder): builder.StartObject(5)
def MessageAddTime(builder, time): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(time), 0)
def MessageAddPropP(builder, propP): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(propP), 0)
def MessageAddPropQ(builder, propQ): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(propQ), 0)
def MessageAddPropR(builder, propR): builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(propR), 0)
def MessageAddPropS(builder, propS): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(propS), 0)
def MessageEnd(builder): return builder.EndObject()
