# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Timescales

import flatbuffers

class NullableInt64(object):
    __slots__ = ['_tab']

    # NullableInt64
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NullableInt64
    def Value(self): return self._tab.Get(flatbuffers.number_types.Int64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateNullableInt64(builder, value):
    builder.Prep(8, 8)
    builder.PrependInt64(value)
    return builder.Offset()
